# Generated by Django 5.2 on 2025-04-25 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use mayúsculas y números', regex='^[A-Z0-9]+$')], verbose_name='Matrícula')),
                ('apellido_paterno', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios', regex='^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$')], verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios', regex='^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$')], verbose_name='Apellido Materno')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios', regex='^[A-Za-zÁÉÍÓÚáéíóúñÑ ]+$')], verbose_name='Nombre(s)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
                'indexes': [models.Index(fields=['apellido_paterno', 'apellido_materno'], name='students_es_apellid_c717c8_idx'), models.Index(fields=['matricula'], name='students_es_matricu_14d77f_idx')],
            },
        ),
    ]
