# Generated by Django 5.2.1 on 2025-05-20 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_estudiante_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(blank=True, max_length=255, null=True)),
                ('entrada', models.CharField(blank=True, max_length=255, null=True)),
                ('acciones', models.CharField(blank=True, max_length=255, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='students.estudiante')),
            ],
        ),
    ]
