# Generated by Django 5.2 on 2025-04-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('estudiante_matricula', models.CharField(max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro Activo',
                'verbose_name_plural': 'Registros Activos',
            },
        ),
        migrations.CreateModel(
            name='RegistroHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('estudiante_matricula', models.CharField(max_length=20)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
            options={
                'verbose_name': 'Registro Histórico',
                'verbose_name_plural': 'Registros Históricos',
            },
        ),
    ]
